# -*- coding: utf-8 -*-
"""
Created on Mon Jun  5 14:01:04 2023

@author: George LAZAROIU
"""

"""
CAMERA PARAMETERS
"""
CAMERA_FRAME_WIDTH = 320        
CAMERA_FRAME_HEIGHT = 240


"""
FEED DISPLAY OPTIONS
"""
DISPLAY_ALL_FEED = 0
DISPLAY_FINAL_FEED = 1
DONT_DISPLAY_FEED = 2
DISPLAY_ALL_LINE_DETECTION_FEED = 3
DISPLAY_ALL_OBJECT_DETECTION_FEED = 4 

"""
DRIVE MODE
"""
ALL_SYSTEMS_ON = 0
ONLY_LANE_DETECTION = 1
ONLY_OBJECT_RECOGNITION = 2

"""
CONTROLLER DEFINES
"""
MAX_SPEED = 100
INITIAL_STEERING_ANGLE = 90
MIN_STEERING_ANGLE = 55
MAX_STEERING_ANGLE = 125
STOP_SPEED_RATIO = 0
DEFAULT_SPEED_RATIO = 1
SPEED_RATIO_40 = 1.5
SPEED_RATIO_60 = 2

"""
LANE DETECTOR DEFINES
"""
BLUE_DETECTION_THRESHOLD_LOWER_BOUND = [80, 90, 20]
BLUE_DETECTION_THRESHOLD_UPPER_BOUND = [125, 255, 255]
REGION_OF_INTEREST_RATIO = 0.5
SEGMENT_DETECTION_VOTES_THRESHOLD = 12
MIN_LINE_DETECTION_LENGTH = 9
MAX_LINE_DETECTION_GAP = 4
CAMERA_OFFSET = 0.045
MAX_ANGLE_DEVIATION_FOR_2_LINES = 4.5
MAX_ANGLE_DEVIATION_FOR_1_LINES = 1.4
LANE_COLOR = (0, 255, 0)
LANE_WIDTH = 10
HEADING_LINE_COLOR = (0, 0, 255)
HEADING_LINE_WIDTH = 5

"""
SIGN DETECTOR DEFINES
"""
MODEL_PATH = '/home/rasberrypi/Licenta2023_Lazaroiu_George/Detectare_Semne_Circulatie/sign_detection.tflite'
LABELS_PATH = '/home/rasberrypi/Licenta2023_Lazaroiu_George/Detectare_Semne_Circulatie/labels.txt'
FONT_SCALE = 0.5
FONT_COLOR = (255, 255, 255)
BOX_COLOR = (0, 0, 255)
BOX_LINE_WIDTH = 1
LINE_TYPE = 2
CLOSE_OBJECT_TRESHOLD = 0.2
SPEED_60 = "Speed_60"
SPEED_40 = "Speed_40"
SPEED_20 = "Speed_20"
RED_LIGHT = "RedLight"
GREEN_LIGHT = "GreenLight"
STOP = "Stop"
